language: java

#install: install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
  - oraclejdk8

#sudo: false
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

after_success:
  - mvn jacoco:report coveralls:report